-- require("noice").setup({
--     cmdline = {
--         enabled = true,
--         view = "cmdline",
--         format = {
--             cmdline = { title = '', icon = '  ' },
--             lua = { title = '', icon = ' 󰢱 ' },
--             help = { title = '', icon = ' 󰋖 ' },
--             input = { title = '', icon = '  ' },
--             filter = { title = '', icon = '  ' },
--         },
--     },
--     messages = {
--         enabled = true,            -- enables the Noice messages UI
--         view = "notify",           -- default view for messages
--         view_error = "notify",     -- view for errors
--         view_warn = "notify",      -- view for warnings
--         view_history = "messages", -- view for :messages
--     },
--     views = {
--         cmdline_popup = {
--             border = {
--                 padding = { 0, 1 },
--             },
--         },
--     },
--     lsp = {
--         progress = {
--             enabled = false,
--         },
--         -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
--         override = {
--             ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
--             ["vim.lsp.util.stylize_markdown"] = true,
--             ["cmp.entry.get_documentation"] = true,
--         },
--     },
--     -- you can enable a preset for easier configuration
--     presets = {
--         bottom_search = true,         -- use a classic bottom cmdline for search
--         command_palette = true,       -- position the cmdline and popupmenu together
--         long_message_to_split = true, -- long messages will be sent to a split
--         inc_rename = false,           -- enables an input dialog for inc-rename.nvim
--         lsp_doc_border = false,       -- add a border to hover docs and signature help
--     },
-- })
