format = """
$hostname$directory$c$python$java$lua$rust
$character
"""
right_format = "$git_branch$git_commit$git_state$git_status"

[hostname]
disabled = false
ssh_only = true
style = "bold #ff5f00"
format = "[$hostname]($style):"

[character]
success_symbol = "[⮑](#aaaaaa) "
error_symbol = "[⮑](#c82829) "

[directory]
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false
read_only = " "
read_only_style = "#c82829"
style = "blck"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_commit]
style = "#875fff"
format = "[\\($hash$tag\\)]($style)"

[git_branch]
symbol = ""
style = "#aaaaaa"
format = "[$symbol$branch]($style)"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
style = "bold #875fff"
format = "([\\[$all_status$ahead_behind\\]]($style))"

[python]
format = "via [$symbol$version]($style)"
symbol = " "

[aws]
symbol = "  "
format = "via [$symbol$version]($style)"

[buf]
symbol = " "
format = "via [$symbol$version]($style)"

[c]
symbol = " "
format = "via [$symbol$version]($style)"

[conda]
symbol = " "
format = "via [$symbol$version]($style)"

[dart]
symbol = " "
format = "via [$symbol$version]($style)"

[docker_context]
symbol = " "
format = "via [$symbol$version]($style)"

[elixir]
symbol = " "
format = "via [$symbol$version]($style)"

[elm]
symbol = " "
format = "via [$symbol$version]($style)"

[golang]
symbol = " "
format = "via [$symbol$version]($style)"

[guix_shell]
symbol = " "
format = "via [$symbol$version]($style)"

[haskell]
symbol = " "
format = "via [$symbol$version]($style)"

[haxe]
symbol = "⌘ "
format = "via [$symbol$version]($style)"

[hg_branch]
symbol = " "
format = "via [$symbol$version]($style)"

[java]
symbol = " "
format = "via [$symbol$version]($style)"

[julia]
symbol = " "
format = "via [$symbol$version]($style)"

[lua]
symbol = " "
format = "via [$symbol$version]($style)"

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "
format = "via [$symbol$version]($style)"

[nim]
symbol = " "
format = "via [$symbol$version]($style)"

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "
format = "via [$symbol$version]($style)"

[rust]
symbol = " "
format = "via [$symbol$version]($style)"

[scala]
symbol = " "

[spack]
symbol = "🅢 "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "